### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by gdevelek** [bioidiap/spear#7]
Hi folks,

Please help me out with this problem:

I have installed bob on an Ubuntu host, I have run "python bootstrap.py" in bob.spear, and when I run ./bin/buildout, I get  an error with bob-python and xbob (error at the end):

root@master:/data/sw/bob.spear-1.1.3# ./bin/buildout
Develop: '/data/sw/bob.spear-1.1.3/.'
Installing scripts.
Develop distribution: matplotlib 1.2.1
uses namespace packages but the distribution does not require distribute.
Getting distribution for 'xbob.sox'.

Installed /tmp/easy_install-KA2o2G/xbob.sox-1.1.0/xbob.extension-0.2.1-py2.7.egg
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1985, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1966, in with_ei_usage
    return f()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1989, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 377, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 647, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 842, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1122, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1108, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 33, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 81, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 35, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 72, in <module>
    'Natural Language :: English',
  File "/tmp/easy_install-KA2o2G/xbob.sox-1.1.0/xbob.extension-0.2.1-py2.7.egg/xbob/extension/__init__.py", line 168, in __init__
  File "/tmp/easy_install-KA2o2G/xbob.sox-1.1.0/xbob.extension-0.2.1-py2.7.egg/xbob/extension/__init__.py", line 48, in pkgconfig
RuntimeError: PkgConfig did not find package bob-python. Output:
Package bob-python was not found in the pkg-config search path.
Perhaps you should add the directory containing `bob-python.pc'
to the PKG_CONFIG_PATH environment variable
No package 'bob-python' found
An error occured when trying to install xbob.sox 1.1.0. Look above this message for any errors that were output by easy_install.
While:
  Installing scripts.
  Getting distribution for 'xbob.sox'.
Error: Couldn't install: xbob.sox 1.1.0

**Comment by bzsy** [comment]
Hello,

I have install bob bob-dev sox libsox-dev on Ubuntu, using 
* $ sudo apt-get install bob bob-dev sox libsox-dev

````
bzsy@ubuntu:~/bob.spear-1.1.8$ dpkg --list|grep bob
ii  bob                                                   1.2.2-0~ppa4~trusty1                                amd64        Toolbox for Biometrics, Machine Learning and Signal Processing
ii  bob-dev                                               1.2.2-0~ppa4~trusty1                                all          Toolbox for Biometrics, Machine Learning and Signal Processing
````

````
bzsy@ubuntu:~/bob.spear-1.1.8$ dpkg --list|grep sox
ii  libsox-dev:amd64                                      14.4.1-3ubuntu1                                     amd64        Development files for the SoX library
ii  libsox-fmt-all:amd64                                  14.4.1-3ubuntu1                                     amd64        All SoX format libraries
ii  libsox-fmt-alsa:amd64                                 14.4.1-3ubuntu1                                     amd64        SoX alsa format I/O library
ii  libsox-fmt-ao:amd64                                   14.4.1-3ubuntu1                                     amd64        SoX Libao format I/O library
ii  libsox-fmt-base:amd64                                 14.4.1-3ubuntu1                                     amd64        Minimal set of SoX format libraries
ii  libsox-fmt-mp3:amd64                                  14.4.1-3ubuntu1                                     amd64        SoX MP2 and MP3 format library
ii  libsox-fmt-oss:amd64                                  14.4.1-3ubuntu1                                     amd64        SoX OSS format I/O library
ii  libsox-fmt-pulse:amd64                                14.4.1-3ubuntu1                                     amd64        SoX PulseAudio format I/O library
ii  libsox2:amd64                                         14.4.1-3ubuntu1                                     amd64        SoX library of audio effects and processing
ii  sox                                                   14.4.1-3ubuntu1                                     amd64        Swiss army knife of sound processing
````

but when I run ./bin/buildout, there is a error 
````
bzsy@ubuntu:~/bob.spear-1.1.8$ ./bin/buildout
Develop: '/home/bzsy/bob.spear-1.1.8/.'
/home/bzsy/bob.spear-1.1.8/eggs/setuptools-8.3-py2.7.egg/pkg_resources/__init__.py:2448: PEP440Warning: 'xdiagnose (3.6.3build2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/home/bzsy/bob.spear-1.1.8/eggs/setuptools-8.3-py2.7.egg/pkg_resources/__init__.py:2448: PEP440Warning: 'python-debian (0.1.21-nmu2ubuntu2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Installing scripts.
Getting distribution for 'bob>=1.2.0'.
While:
  Installing scripts.
  Getting distribution for 'bob>=1.2.0'.
Error: Couldn't find a distribution for 'bob>=1.2.0'.
````
Have I got something wrong when installed bob? Please help me , thanks a lot!

**Comment by siebenkopf** [comment]
The buildout system has lately changed. It requires a new bootstrap-buildout.py, which you can download here:
$ wget https://bootstrap.pypa.io/bootstrap-buildout.py

Then, please remove all files and directories that were automatically generated, which are usually:
$ rm -rf bin build develop-eggs .installed.cfg .mr.developer.cfg eggs parts *.egg-info

And run bootstrap and buildout again:
$ python bootstrap-buildout.py
$ bin/buildout

I hope this solves your problem.

Cheers
Manuel

**Comment by bzsy** [comment]
Thanks for your reply, but it seems the error still exist:
```
bzsy@ubuntu:~/bob.spear-1.1.8$ wget https://bootstrap.pypa.io/bootstrap-buildout.py
--2015-01-13 00:13:55--  https://bootstrap.pypa.io/bootstrap-buildout.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 103.245.222.175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|103.245.222.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6501 (6.3K) [text/x-python]
Saving to: ‘bootstrap-buildout.py’

100%[============================================================================================>] 6,501       --.-K/s   in 0s      

2015-01-13 00:13:56 (171 MB/s) - ‘bootstrap-buildout.py’ saved [6501/6501]
```

```
bzsy@ubuntu:~/bob.spear-1.1.8$ rm -rf bin build develop-eggs .installed.cfg .mr.developer.cfg eggs parts *.egg-info
```

```
bzsy@ubuntu:~/bob.spear-1.1.8$ python bootstrap-buildout.py
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-11.3.1.zip
Extracting in /tmp/tmpH7y58u
Now working in /tmp/tmpH7y58u/setuptools-11.3.1
Building a Setuptools egg in /tmp/tmpP9Mw2t
warning: no files found matching '*.c' under directory 'tests'
warning: no files found matching '*.pyx' under directory 'tests'
/tmp/tmpP9Mw2t/setuptools-11.3.1-py2.7.egg
/usr/local/lib/python2.7/dist-packages/setuptools-8.3-py2.7.egg/pkg_resources/__init__.py:2448: PEP440Warning: 'xdiagnose (3.6.3build2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/dist-packages/setuptools-8.3-py2.7.egg/pkg_resources/__init__.py:2448: PEP440Warning: 'python-debian (0.1.21-nmu2ubuntu2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Creating directory '/home/bzsy/bob.spear-1.1.8/bin'.
Creating directory '/home/bzsy/bob.spear-1.1.8/parts'.
Creating directory '/home/bzsy/bob.spear-1.1.8/eggs'.
Creating directory '/home/bzsy/bob.spear-1.1.8/develop-eggs'.
Generated script '/home/bzsy/bob.spear-1.1.8/bin/buildout'.
```
```
bzsy@ubuntu:~/bob.spear-1.1.8$ ./bin/buildout
Develop: '/home/bzsy/bob.spear-1.1.8/.'
/home/bzsy/bob.spear-1.1.8/eggs/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'xdiagnose (3.6.3build2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/home/bzsy/bob.spear-1.1.8/eggs/setuptools-11.3.1-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'python-debian (0.1.21-nmu2ubuntu2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Getting distribution for 'xbob.buildout'.
/usr/local/lib/python2.7/dist-packages/setuptools-8.3-py2.7.egg/pkg_resources/__init__.py:2448: PEP440Warning: 'xdiagnose (3.6.3build2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/dist-packages/setuptools-8.3-py2.7.egg/pkg_resources/__init__.py:2448: PEP440Warning: 'python-debian (0.1.21-nmu2ubuntu2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Got xbob.buildout 0.4.7.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
/usr/local/lib/python2.7/dist-packages/setuptools-8.3-py2.7.egg/pkg_resources/__init__.py:2448: PEP440Warning: 'xdiagnose (3.6.3build2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/usr/local/lib/python2.7/dist-packages/setuptools-8.3-py2.7.egg/pkg_resources/__init__.py:2448: PEP440Warning: 'python-debian (0.1.21-nmu2ubuntu2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Got zc.recipe.egg 2.0.1.
Installing scripts.
Getting distribution for 'bob>=1.2.0'.
While:
  Installing scripts.
  Getting distribution for 'bob>=1.2.0'.
Error: Couldn't find a distribution for 'bob>=1.2.0'.
```

**Comment by siebenkopf** [comment]
First of all, it is weird that setuptools-8.3 from the system path is used, rather than the version 11.3.1 from the eggs. 

I guess that this is an issue of xbob.buildout, which is the bob-1.x compatible (old) version of bob.buildout. I remember that we applied a lot of fixes to get the installation directories right. I will need to have a closer look into what might cause your trouble.

**Comment by bzsy** [comment]
The error is occurs on Ubuntu 14.04, and I just try @siebenkopf 's advice on an new computer (Ubuntu 12.04), It works well!  I guess maybe there are something others wrong on my old host,  Your reply is very helpful, Thanks a lot!!

**Comment by LollipopLollipop** [comment]
Hi, 
I ran into a problem when trying to install spear on Ubuntu 12.04.
I have already installed bob, bob-dev, sox and libsox-dev:
![screen shot 2015-03-01 at 3 46 20 pm](https://cloud.githubusercontent.com/assets/8728198/6432741/41a5ae76-c02a-11e4-9ab2-2148d0afff54.png)

The error messages said:
Scanning dependencies of target bob_io_base
make[2]: Leaving directory `/tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/build/build_cmake/bob_io_base'
make -f CMakeFiles/bob_io_base.dir/build.make CMakeFiles/bob_io_base.dir/build
make[2]: Entering directory `/tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/build/build_cmake/bob_io_base'
/usr/bin/cmake -E cmake_progress_report /tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/build/build_cmake/bob_io_base/CMakeFiles 1
[  5%] Building CXX object CMakeFiles/bob_io_base.dir/tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/bob/io/base/cpp/CodecRegistry.cpp.o
/usr/bin/c++   -Dbob_io_base_EXPORTS -DHAVE_HDF5=1 -DHDF5_VERSION=\"None\" -DPY_ARRAY_UNIQUE_SYMBOL=BOB_NUMPY_C_API -DNO_IMPORT_ARRAY=1 -DHAVE_BLITZ=1 -DBLITZ_VERSION=\"0.10\" -std=c++0x -pedantic -Wall -pthread -O3 -g0 -DNDEBUG -mtune=generic  -fPIC -I/tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/bob/io/base/include -I/tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/.eggs/bob.blitz-2.0.3-py2.7-linux-x86_64.egg/bob/blitz/include -isystem /usr/lib/python2.7/dist-packages/numpy/core/include    -o CMakeFiles/bob_io_base.dir/tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/bob/io/base/cpp/CodecRegistry.cpp.o -c /tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/bob/io/base/cpp/CodecRegistry.cpp
In file included from /tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/bob/io/base/include/bob.io.base/File.h:16:0,
                 from /tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/bob/io/base/include/bob.io.base/CodecRegistry.h:17,
                 from /tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/bob/io/base/cpp/CodecRegistry.cpp:15:
/tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/bob/io/base/include/bob.io.base/blitz_array.h:19:28: fatal error: bob.core/check.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/bob_io_base.dir/tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/bob/io/base/cpp/CodecRegistry.cpp.o] Error 1
make[2]: Leaving directory `/tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/build/build_cmake/bob_io_base'
make[1]: *** [CMakeFiles/bob_io_base.dir/all] Error 2
make[1]: Leaving directory `/tmp/easy_install-57Zdpc/bob.learn.misc-2.0.1/temp/easy_install-WFypsW/bob.learn.linear-2.0.3/temp/easy_install-h5QFMb/bob.learn.activation-2.0.2/temp/easy_install-k8MKuz/bob.io.base-2.0.4/build/build_cmake/bob_io_base'
make: *** [all] Error 2
error: Setup script exited with error: None
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
    info('process shutting down')
TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/bob/core/__init__.py", line 108, in reset_all_streams
    debug.reset("stderr")
AttributeError: 'NoneType' object has no attribute 'reset'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
    info('process shutting down')
TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/bob/core/__init__.py", line 108, in reset_all_streams
    debug.reset("stderr")
AttributeError: 'NoneType' object has no attribute 'reset'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
    info('process shutting down')
TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/bob/core/__init__.py", line 108, in reset_all_streams
    debug.reset("stderr")
AttributeError: 'NoneType' object has no attribute 'reset'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
    info('process shutting down')
TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/bob/core/__init__.py", line 108, in reset_all_streams
    debug.reset("stderr")
AttributeError: 'NoneType' object has no attribute 'reset'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/bob/core/__init__.py", line 108, in reset_all_streams
    debug.reset("stderr")
AttributeError: 'NoneType' object has no attribute 'reset'
An error occurred when trying to install bob.learn.misc 2.0.1. Look above this message for any errors that were output by easy_install.
While:
  Installing scripts.
  Getting distribution for 'bob.learn.misc'.
Error: Couldn't install: bob.learn.misc 2.0.1


Any help would be much appreciated! Thanks!

**Comment by siebenkopf** [comment]
You're suffering from our restructuring of Bob. It appears that bob.spear still requires Bob 1, while it takes one of the new packages, which requires Bob 2. Unfortunately, those two versions of Bob are mutually incompatible.

Unfortunately, it is not very clear, which of the dependent packages causes the trouble. Could you please clean up your package installation (or simply try it out in a new directory), run:

$ python bootstrap.py
$ .bin/buildout -vv

and report **the complete** install log?

Thank you
Manuel

P.S.: You can also try out the solution proposed here: https://github.com/bioidiap/spear/issues/7#issuecomment-69549590
If you try, could you please report if this has worked?

**Comment by siebenkopf** [comment]
Maybe I should ask first questions first: How did you download bob.spear? From PyPI (e.g., using pip) or from GitHub?

**Comment by LollipopLollipop** [comment]
Thanks very much for your timely response! The installation failed for spear v1.2 and v2.0, but succeeded for v1.8 which I downloaded from https://pypi.python.org/pypi/bob.spear.

**Comment by SteveK2** [comment]
Seems I'm having the same problem on a Mac.
Can someone explain what's actually happening?

Did this as above:
$ wget https://bootstrap.pypa.io/bootstrap-buildout.py

Then, please remove all files and directories that were automatically generated, which are usually:
$ rm -rf bin build develop-eggs .installed.cfg .mr.developer.cfg eggs parts *.egg-info

And run bootstrap and buildout again:
$ python bootstrap-buildout.py
$ bin/buildout

Got this error:
...
Installing scripts.
Getting distribution for 'bob>=1.2.0'.
While:
  Installing scripts.
  Getting distribution for 'bob>=1.2.0'.
Error: Couldn't find a distribution for 'bob>=1.2.0'.

**Comment by anjos** [comment]
Could you please check:

```sh
which python
```

? And report it back.

**Comment by SteveK2** [comment]
Steves-Mac-mini:bob.spear-1.1.8 steve$ which python
/usr/bin/python

Steves-Mac-mini:bob.spear-1.1.8 steve$ port select --list python
Available versions for python:
none (active)
python26-apple
python27
python27-apple

**Comment by anjos** [comment]
This is **not** the same problem. Please note our Trusty binaries are **not** working as of today. Ubuntu 14.04 is not a supported platform presently for Bob v1.

As for your issue, @SteveK2, refer to our installation instructions. It is well documented there:

https://github.com/idiap/bob/wiki/Dependencies#mac-osx-with-macports.

**Comment by comihai** [comment]
I created a virtual machine with Ubuntu 14.04.
I tried to install bob.spear but i came across an error.

mihai@mihai-PC:~/bob.spear-1.1.2$ ./bin/buildout -v
Develop: '/home/mihai/bob.spear-1.1.2/.'
Installing 'xbob.buildout'.
We have no distributions for xbob.buildout that satisfies 'xbob.buildout'.
Getting distribution for 'xbob.buildout'.
Running easy_install:
"/usr/bin/python" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/mihai/bob.spear-1.1.2/eggs/tmpr3GXkY" "-q" "/tmp/tmparGOWhget_dist/xbob.buildout-1.0.3.zip"
path=/usr/local/lib/python2.7/dist-packages

Got xbob.buildout 1.0.3.
Picked: xbob.buildout = 1.0.3
Getting required 'zc.recipe.egg>=2.0.0a3'
We have no distributions for zc.recipe.egg that satisfies 'zc.recipe.egg>=2.0.0a3'.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Running easy_install:
"/usr/bin/python" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/mihai/bob.spear-1.1.2/eggs/tmpDmcIVz" "-q" "/tmp/tmpk2rn7pget_dist/zc.recipe.egg-2.0.1.tar.gz"
path=/usr/local/lib/python2.7/dist-packages

Got zc.recipe.egg 2.0.1.
Picked: zc.recipe.egg = 2.0.1
Installing scripts.
Installing 'bob>=1.2.0'.
We have no distributions for bob that satisfies 'bob>=1.2.0'.
Getting distribution for 'bob>=1.2.0'.
While:
Installing scripts.
Getting distribution for 'bob>=1.2.0'.
Error: Couldn't find a distribution for 'bob>=1.2.0'.

Has someone resolved this problem in Ubuntu 14.04 ?

**Comment by comihai** [comment]
I tried to install bob.spear on Ubuntu 12.04 but i met again with  some errors.

AttributeError: 'NoneType' object has no attribute 'reset'
An error occurred when trying to install bob.learn.em 2.0.1. Look above this message for any errors that were output by easy_install.
While:
  Installing scripts.
  Getting distribution for 'bob.learn.em'.
Error: Couldn't install: bob.learn.em 2.0.1

Did you (@bzsy) manage to install on ubuntu 12.04 ?

**Comment by bzsy** [comment]
@comihai . I just update the file bootstrap-buildout.py, and it works well on Ubuntu 12.04. You may try steps as:
```
$ sudo add-apt-repository ppa:biometrics/bob
$ sudo apt-get update
$ sudo apt-get install bob bob-dev sox libsox-dev
$ wget https://pypi.python.org/packages/source/b/bob.spear/bob.spear-1.1.8.zip
$ unzip bob.spear-1.1.8.zip
$ cd bob.spear-1.1.8
$ wget https://bootstrap.pypa.io/bootstrap-buildout.py 
$ python bootstrap-buildout.py
$ .bin/buildout
```

**Comment by comihai** [comment]
@bzsy . I tried on Ubuntu 12.04 but i got an error at last command `./bin/buildout `
While:
  Installing scripts.
  Getting distribution for 'xbob.db.verification.utils'.
Error: Couldn't find a distribution for 'xbob.db.verification.utils'.

Have you any idea why this happens?

**Comment by siebenkopf** [comment]
@comihai: This looks like an issue with PyPI. Did you see any exception like "couldn't connect" or "timeout" while installing? If yes, please try to run ``.bin/buildout`` again.

If the error persists, could you please send the **complete** error log, so that we might get a grasp on your problem?

**Comment by comihai** [comment]
Thanks very much for your timely response! I got a timeout at downloading xbob.db.verification.utils ..so i downloaded this package manually and it worked. I run again `./bin/buildout` and some scripts were generated in the bin directory.
Hoping that these tools were installed well, i kindly ask you if you could give me some links containing some examples for a newbie of using these tools for speech recognition.

**Comment by khoury** [comment]
Hello,
Short answer: This tool implements only state-of-the-art speaker recognition toolchain.
You can use spear / bob to generate several steps (feature extraction, modeling) of your speech recognition toolchain. but it's far from being complete. I suggest you use other tools (e.g. HTK, Kaldi) to meet your needs.
Thanks,
Elie

**Comment by siebenkopf** [comment]
There was no need to download the package by hand, you just needed to repeat the ``./bin/buildout``. In fact, you can delete the package that you have downloaded manually.

For running the examples, I am not the right person to ask. Maybe you should open a new discussion in our mailing list:
https://groups.google.com/forum/?fromgroups#!forum/bob-devel

**Comment by comihai** [comment]
Hi @khoury . I have installed HTK Speech Recognition Tool on Windows 7. I followed this tutorial http://htk.eng.cam.ac.uk/docs/inst-win.shtml .There is just a testing part on a demo package. I would like to give me some examples of using this tool if possible.

**Comment by smarcel** [comment]
@comihai we already provide a lot of support for bob, facereclib and spear, I don't think we are able to provide support also for HTK nor Kaldi.

**Comment by saikrishnar** [comment]
Hi,

The issue persists on Ubuntu 14.04.


Installing scripts.
Getting distribution for 'bob>=1.2.0'.
While:
  Installing scripts.
  Getting distribution for 'bob>=1.2.0'.
Error: Couldn't find a distribution for 'bob>=1.2.0'

Please help

**Comment by laurentes** [comment]
Hello,

The PyPI version of spear is outdated (it relies on bob v1) and has not been updated for a while.
Could you?
1. Install bob dependencies (see https://github.com/idiap/bob/wiki/Dependencies)
2. Remove any bob v1 installation (e.g. sudo apt-get remove --purge bob bob-dev)
3. Clone the spear package from github
4. Rerun the installation (python bootstrap-buildout.py ; ./bin/buildout)

Thanks

**Comment by saikrishnar** [comment]
Thanks for the prompt reply.

Its getting installed now.

**Comment by saikrishnar** [comment]
When I try to run the verification on Voxforge data, this is the error that comes up.


File "./bin/spkverif_gmm.py", line 45, in <module>
    sys.exit(spear.script.spkverif_isv.main())
  File "/usr/local/lib/python2.7/dist-packages/bob.spear-1.1.2-py2.7.egg/spear/script/spkverif_isv.py", line 492, in main
    speaker_verify(args)
  File "/usr/local/lib/python2.7/dist-packages/bob.spear-1.1.2-py2.7.egg/spear/script/spkverif_isv.py", line 460, in speaker_verify
    executor.execute_tool_chain()
  File "/usr/local/lib/python2.7/dist-packages/bob.spear-1.1.2-py2.7.egg/spear/script/spkverif_isv.py", line 81, in execute_tool_chain
    self.m_tool_chain.extract_features(self.m_feature_extractor, self.m_tool, force = self.m_args.force)
  File "/usr/local/lib/python2.7/dist-packages/bob.spear-1.1.2-py2.7.egg/spear/toolchain/ToolChain.py", line 224, in extract_features
    feature = extractor(wav_file, vad_file)
  File "/usr/local/lib/python2.7/dist-packages/bob.spear-1.1.2-py2.7.egg/spear/feature_extraction/Cepstral.py", line 55, in __call__
    rate_wavsample = utils.read(input_file)
  File "/usr/local/lib/python2.7/dist-packages/bob.spear-1.1.2-py2.7.egg/spear/utils/__init__.py", line 91, in read
    import xbob.sox
ImportError: No module named xbob.sox


Please suggest. I've installed bob again. Yes. I've sox and sox-dev too.

**Comment by khoury** [comment]
You are still using the old source code of spear. The new one does not contain dependencies to xbob.sox. @laurentes asked you to clone the github repository. We will upload the new version very soon to pypi.

**Comment by saikrishnar** [comment]
I've re run the clone ( at another location in the computer)

Deleted bob as informed.

Same error persists.

Please help.






Thanks and Regards,

Sai Krishna
Researcher in Speech Sciences,
Speech and Vision Lab,
International Institute of Information Technology- Hyderabad

researchweb.iiit.ac.in/~saikrishna.r

%%%%%%%%%%%%%

Try n learn* every bit of* your core ....and a *bit of every* other
Research field.

Jg jut *OQ* ibse, zpv ibwfo'u usjfe fopvhi
 #&%// - Reverse ceaser crypted with '1'

%%%%%%%%%%%%%

**Comment by khoury** [comment]
Sorry, but from your error logs, it's clear that you were using "bob.spear-1.1.2" which is using bob 1 and is not the latest version on pypi nor github. Current package does not depend at all from sox. 

I also recommend you to move to this package that was released recently:
https://github.com/bioidiap/bob.bio.spear/

**Comment by saikrishnar** [comment]
Sure. Will try this one.








Thanks and Regards,

Sai Krishna
Researcher in Speech Sciences,
Speech and Vision Lab,
International Institute of Information Technology- Hyderabad

researchweb.iiit.ac.in/~saikrishna.r

%%%%%%%%%%%%%

Try n learn* every bit of* your core ....and a *bit of every* other
Research field.

Jg jut *OQ* ibse, zpv ibwfo'u usjfe fopvhi
 #&%// - Reverse ceaser crypted with '1'

%%%%%%%%%%%%%
